// reactjs-tutorial/src/components/layouts/Layout.jsx
export default function Layout(props) {
    const { children } = props

    const header = (
        <header>
            <h1 className="text-medium text-gradient">
                Unalive
            </h1>
        </header>
    )
    
    const footer =(
        <footer>
            <small>Created By:</small>
            <a target="blank" href="https://www.linkedin.com/in/adam-mackey-611b13220/">
                <img alt="pfp" src="https://media.licdn.com/dms/image/v2/C5603AQGHwknAYchapw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1631635420449?e=1750896000&v=beta&t=N_DUnufpW6VS9n4XHlEA3seo2s4VZgLS2hdy-ocVZnc"/>
                <p>@MackInSpace</p>
            </a>
        </footer>
    )

    return (
        <>
            {header}
            <main>
                {children}
            </main>
            {footer}
        </>
    )
}

// svelte-tutorial/src/lib/layouts/Layout.svelte
<script>
  import { calculateTimeLeft, getLifePercentageLived } from "../../utils";

    const {headache} = $props();

    let birthDate = '1995-06-15';
    let lifeExpectancy = 80
    let name = 'adam'

    let data = calculateTimeLeft(birthDate, lifeExpectancy);
    let percentage = getLifePercentageLived(birthDate, lifeExpectancy);
</script>

<header>
    <h1 class="text-medium text-gradient">Unalive</h1>
</header>

<main>
    {@render headache({ data, birthDate, name, percentage, lifeExpectancy })}
</main>
<footer>
    <small>Created By:</small>
    <a target="black" href="/">
        <img src="https://media.licdn.com/dms/image/v2/C5603AQGHwknAYchapw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1631635420449?e=1753920000&v=beta&t=SsHBoJOOMAModgIHYf7fTAO9vVaE2d4pC-shBl89PAg" alt="pfp" />
        <p>@Adam-Mackey</p>
        <i class="fa-brands fa-linkedin-in"></i>
    </a>
</footer>

<style></style>
