// reactjs-tutorial/src/components/Form.jsx
import React, { useState } from 'react'

export default function Form(props) {
    const { handleCloseModal, handleUpdateData } = props
    const [name, setName] = useState('Adam')
    const [lifeExpectancy, setLifeExpectancy] = useState(80)
    const [month, setMonth] = useState(1)
    const [day, setDay] = useState(1)
    const [year, setYear] = useState(new Date().getFullYear())

    const days = Array.from({ length: 31 }, (_, i) => i + 1)
    const months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ]
    const years = Array.from({ length: 100 }, (_, i) => new Date().getFullYear() - i)

    return (
        <section id="form">
            <div>
                <h4 className='text-gradient'>Your Details</h4>
                <button onClick={handleCloseModal} className='link-button'>
                    <i className='fa-solid fa-xmark' />
                </button>
            </div>
            <div>
                <label>Name</label>
                <input value={name} onChange={(e) => {
                    setName(e.target.value)
                }} type='text' required />
            </div>
            <div>
                <label>Date of Birth</label>
                <div className='bday'>
                    <select value={day}
                        onChange= {(e) => {
                            setDay(e.target.value)
                        }}>
                        {days.map((d) => {
                            return (
                                <option key={d} value={d}>{d}</option>
                            )
                        })}
                    </select>
                    <select value={month}
                        onChange={(e) => {
                            setMonth(e.target.value)
                        }}>
                        {months.map((m, i) => {
                            return (
                                <option key={i} value={i + 1}>{m}</option>
                            )
                        })}
                    </select>
                    <select value={year}
                        onChange={(e) => {
                            setYear(e.target.value)
                        }}>
                        {years.map((y) => {
                            return (
                                <option key={y} value={y}>{y}</option>
                            )
                        })}
                    </select>
                </div>
            </div>
            <div>
                <label>Life Expectancy (years)</label>
                <input value={lifeExpectancy} onChange={(e) => {
                    setLifeExpectancy(e.target.value)
                }} type='number' max={120} required />
            </div>
            <button onClick={() => {
                handleCloseModal(name, `${year}-${month}-${day}`, lifeExpectancy)
            }}>
                Save
            </button>
        </section>
    )
}

// vue-tutorial/src/components/Form.vue
<script>
    import { ref } from 'vue'

    const { handleUpdateData, handleCloseModal } = defineProps({
        handleUpdateData: Function,
        handleCloseModal: Function
    })

    const name = ref('')
    const currYear = new Date().getFullYear()
    const day = ref(1)
    const month = ref(1)
    const year = ref(currYear)
    const lifeExpectancy = ref(80)

    //Options
    const days = Array.from({ length: 31 }, (_, i) => i + 1)
    const months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ]
    const years = Array.from({ length: 100 }, (_, i) => currYear + i)

    function handleSave() {
        handleUpdateData(name.value, `${year.value}-${month.value}-${day.value}`, lifeExpectancy.value)
    }
</script>

<template>
    <section id="form">
        <div>
            <h4 class="text-gradient">Your Details</h4>
            <button @click="handleCloseModal" class="link-button">
                <i class="fa-solid fa-xmark"></i>
            </button>
        </div>
        <div>
            <label for="name">Name</label>
            <input type="text" id="name" v-model="name" required />
        </div>
        <div>
            <div>Birthday</div>
            <div class="bday">
                <section>
                    <option v-for="d in days" :value="d" :key="d">
                        {{ d }}
                    </option>
                </section>
                <select v-model="month">
                    <option v-for="(m, index) in months" :key="index" :value="index + 1">
                        {{ m }}
                    </option>
                </select>
                <select v-model="year">
                    <option v-for="y in years" :key="y" :value="y">
                        {{ y }}
                    </option>
                </select>
            </div>
        </div>
        <div>
            <label for="lifeExpectancy">Life Expectancy (years)</label>
            <input type="number" id="lifeExpectancy" v-model="lifeExpectancy" max="120" required />
        </div>
        <button @click="handleSave">Save</button>
    </section>
</template>

<style scoped></style>
