// svelte-tutorial/src/lib/Portal.svelte
<script>
    const { form, handleCloseModal } = $props();
</script>

<div class="portal-container">
    <div 
        role="button" 
        tabindex="0" 
        onkeydown={() => {}} 
        onclick={handleCloseModal} 
        class="portal-underlay"
    >
    </div>
    <div class="portal-content">
        {@render form()}
    </div>
</div>

// vue-tutorial/src/components/Portal.vue
<script setup>
    defineProps({
        showModal: Boolean,
        handleCloseModal: Function
    })
</script>

<template>
    <Teleport v-if="showModal" to="#portal">
        <div class="portal-container">
            <div class="portal-underlay" role="button" tabindex="0" @click="handleCloseModal">
            </div>
            <div class="portal-content">
                <slot />
            </div>
        </div>
    </Teleport>
</template>

<style scoped></style>
