// svelte-tutorial/src/App.svelte
<script>
    import Layout from "./lib/layouts/Layout.svelte";
    import Summary from "./lib/Summary.svelte";
    import Hero from "./lib/Hero.svelte";
    import Clocks from "./lib/Clocks.svelte";
    import Calendar from "./lib/Calendar.svelte";
</script>

<Layout>
    <Hero />
    <Clocks />
    <Calendar />
    <Summary />
 </Layout>

// vue-tutorial/src/App.vue
<script setup>
  import { computed, onMounted, ref, watchEffect } from 'vue'
  import Calendar from './components/Calendar.vue';
  import Clocks from './components/Clocks.vue';
  import Hero from './components/Hero.vue';
  import Layout from './components/Layout.vue';
  import Summary from './components/Summary.vue';
  import Form from './components/Form.vue';

  import { calculateTimeLeft, getLifePercentageLived } from './utils';
  import Protal from './components/Portal.vue';

</script>

<template>
  
</template>

<style scoped>

</style>
