// reactjs-tutorial/src/components/Portal.jsx
import React from "react"
import ReactDom from "react-dom"

export default function Portal (props) {
    const { handleCloseModal, children } = props

    return ReactDom.createPortal (
        <div className='portal-container'>
            <div onClick={handleCloseModal} className="portal-underlay"></div>
            <div className="portal-content">
                {children}
            </div>
        </div>,
        document.getElementById('portal')
    )
}

// svelte-tutorial/src/lib/Portal.svelte
<script>
    const { form, handleCloseModal } = $props();
</script>

<div class="portal-container">
    <div 
        role="button" 
        tabindex="0" 
        onkeydown={() => {}} 
        onclick={handleCloseModal} 
        class="portal-underlay"
    >
    </div>
    <div class="portal-content">
        {@render form()}
    </div>
</div>
